### ISSUE TITLE
Too much memory usage when loading images

### ISSUE THREAD

**Issue by johnnychen94** [JuliaIO/FileIO.jl#202]
For example, Showing lena_gray_512 would cause 1.3GB ram consumption.  Images come from [lena_gray_512.png](https://github.com/cszn/DnCNN/blob/master/testsets/Set12/08.png) and `TestImages`
**Strange** thing is that this issue seems only appear when I use the following ways to read and show image, 

```julia
using FileIO
lena = load("Data/Set12/08.png")
```
```julia
using TestImages
lena = testimage("lena_gray_512")
```

And the following ways just won't
```julia
using Images
lena = load("Data/Set12/08.png")
```
```julia
using Images, TestImages
lena = testimage("lena_gray_512")
```

So I think `Images` takes some additional steps to avoid this issue.

I tried on following configurations, all failed with high ram consumption

* Julia v0.7 + Ubuntu 16.04 + Jupyter notebook + ImageMagick v6.9.10.10
* Julia v1.0 + Ubuntu 16.04 + Jupyter notebook + ImageMagick v6.9.10.10
* Julia v1.0 + MacOS + Jupyter notebook + ImageMagick (lib v6.9.10-4) / QuartzImageIO
* Julia v1.0 + MacOS + Atom Juno  + ImageMagick (lib v6.9.10-4) / QuartzImageIO

**Comment by RalphAS** [comment]
This is almost certainly the problem described in https://github.com/JuliaImages/Images.jl/issues/737.  The trouble is that since ImageMagick and QuartzImageIO have dropped the Images dependency, but still have a Colors dependency, we get expensive SVG display for images in the above cases.
Now that a PNG `show` override is available from the lightweight ImageShow package, those two IO packages should use that as a dependency.  But first we need to tag an ImageShow-compatible version of Images.  Is there any reason to postpone that? @timholy @Evizero

**Comment by Evizero** [comment]
thanks for the reminder: https://github.com/JuliaLang/METADATA.jl/pull/17860

**Comment by johnnychen94** [comment]
Looks like this issue is already fixed.
