### ISSUE TITLE
World Age problem when loading tif and multiplying result by a number

### ISSUE THREAD

**Issue by jwscook** [JuliaIO/FileIO.jl#283]
I've come across a weird problem when I load a Float64 `.tif` file, I get a world age error and I've got no idea why. I've documented the problem in a MWE repo, [FileIOWorldAgeProblem.jl](https://github.com/jwscook/FileIOWorldAgeProblem.jl). Everything about it is explained and/or shown in there.

**Comment by ianshmean** [comment]
I believe the problem is due to FileIO being a lazy loader (the IO packages are only loaded when you actually go to use them), and FileIO is loading the tif loader (QuartzImageIO) into Main after the module FileIOWorldAgeProblem, so has a later world age. Your use of `*` is trying to access a method introduced by `QuartzImageIO.ColorVectorSpace`, which you're not explicitly loading into FileIOWorldAgeProblem, but the problem is it's too new.

The likely fix would be to `using ColorVectorSpace` in FileIOWorldAgeProblem to ensure that the `*` method is loaded in that module in the same world age.

**Comment by johnnychen94** [comment]
Maybe we should document this as an expected behavior somewhere?
