### ISSUE TITLE
SVG format

### ISSUE THREAD

**Issue by sglyon** [JuliaIO/FileIO.jl#49]
I can't seem to find any support for SVG format here. Has anyone thought about this? I'm happy to pitch in to get it working

**Comment by SimonDanisch** [comment]
SVG seems also problematic because it really is just xml? So probably we should really get serious about the container kind of types.

**Comment by spencerlyon2** [comment]
Yeah I'm not an SVG expert by any means, but I think you are right -- just xml.

I looked around a bit and couldn't find much in the Julia ecosystem for reading in an SVG and converting it to something else. I believe that @dcjones accomplishes this somehow for Gadfly/Compose/Cairo, but I haven't had time to dig into that code enough to be sure.

**Comment by SimonDanisch** [comment]
Well, with ImageMagick you would loose the vector information.
Since I have the prejudice that PDF is a pretty complex format, I guess your best bet is to find a c library that does this and wrap it.
From all I know, `Compose` only writes out a subset of `SVG`. I think we currently don't even have the infrastructure to represent the full set of Vector Graphics (with bezier paths, contours etc)

**Comment by ViralBShah** [comment]
Was added in 68b76f6f34680da92a837e9f18c962e74a714833
