### ISSUE TITLE
How to use already installed ImageMagick library?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaIO/FileIO.jl#67]
Hello. I want to load an image whose format is jpg or png. But when I try:
julia> img=load("test.jpg")
The following warning shows up:
WARNING: FileIO.NotInstalledError(:ImageMagick,"")
in checked_import at C:\Users\XXX\.julia\v0.4\FileIO\src\loadsave.jl:12
in load at C:\Users\XXX\.julia\v0.4\FileIO\src\loadsave.jl:79
in load at C:\Users\XXX\.julia\v0.4\FileIO\src\loadsave.jl:42
Library ImageMagick is not installed but can load format: FileIO.File{FileIO.DataFormat{:JPEG}}("test.jpg")
should we install ImageMagick for you? (y/n):

Now, independently from julia, I already installed the latest version of ImageMagick on my system at at C:\Program Files\ImageMagick-7.0.1-Q16. Why doesn't julia recognize this installed ImageMagick? If I type 'y' to the above prompt, along with ImageMagick.jl, all the ImageMagick library items are installed under my .julia\v0.4\ImageMagick\deps\ folder. I do not want to install another version of ImageMagick because it is a waste of space.  How can I use the preinstalled version of ImageMagick library. Please help!

**Comment by timholy** [comment]
There may be two issues here:
- You need the `ImageMagick.jl` package. ImageMagick is a C-library plus executable functions, and you need some julia code to act as "glue" to make the C library callable. So if you didn't already have the ImageMagick.jl package installed, FileIO was correct in prompting you to install it.
- What you probably want is that the `ImageMagick.jl` package to recognize your pre-installed library. That is something that would probably need to be fixed in the `deps/build.jl` file in ImageMagick.jl.

Since it involves system paths, and I don't have a Windows machine, I'm afraid to say that you'll probably have to figure out the fix. As a hint, you might be able to define `MAGICK_HOME` or add some folders to the [search path](https://github.com/JuliaIO/ImageMagick.jl/blob/01d215bb44aeb3f6d560a06c68d93ee66de89dfa/deps/build.jl#L7-L17).

Sorry to redirect you again, but this isn't really a FileIO issue: the fix will have to come in ImageMagick.jl. So I'll close this.

**Comment by timholy** [comment]
Oh, and if you do fix, it, please submit the fix!

**Comment by SimonDanisch** [comment]
Please try out https://github.com/JuliaIO/ImageMagick.jl/pull/28
I still haven't merged it yet, because I couldn't really test it so far...
